src/project/client/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.client, name='client'),
]

src/project/collaborator/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.collaborator, name='collaborator'),
]

src/project/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.CreateContact.as_view(), name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='home/login.html'), name='login'),
]

src/project/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/project/client/models.py
from django.db import models

# Create your models here.

src/project/collaborator/models.py
from django.db import models

# Create your models here.

src/project/home/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField()


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()

src/project/home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        ]


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'avatar',
        ]

src/project/client/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def client(request):
    return HttpResponse("Hello, world. You're at the polls index.")

src/project/collaborator/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def collaborator(request):
    return HttpResponse("Hello, world. You're at the polls index.")

src/project/home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import ProfileCreationForm, SignUpForm
from django.contrib.auth import login, authenticate

# Create your views here.
from .models import Contact


def home(request):
    return render(request, 'home/index.html')


def about(request):
    return render(request, 'home/about.html')


def services(request):
    return render(request, 'home/services.html')


class CreateContact(CreateView):
    model = Contact
    template_name = 'home/contact.html'
    success_url = reverse_lazy('home:home')
    fields = '__all__'


def contact(request):
    return render(request, 'home/contact.html')


def signup(request):
    form = SignUpForm()
    form2 = ProfileCreationForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        form2 = ProfileCreationForm(request.POST, request.FILES)
        if form.is_valid() and form2.is_valid():
            user = form.save()
            profile = form2.save(commit=False)
            profile.user = user
            profile.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
        else:
            print(form.errors)

    return render(request, 'home/signup.html', {'form': form, 'form2': form2})

src/project/home/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700' %}" rel="stylesheet">

    <title>DC Space</title>

    <link rel="stylesheet" type="text/html" href="form1.html">
    <link rel="stylesheet" type="text/html" href="form2.html">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-host-cloud.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>DC <em>Space</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:home' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:services' %}">Our Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:contact' %}">Contact Us</a>
              </li>
            </ul>
          </div>
          <div class="functional-buttons">
            <ul>
              <li><a href="{% url 'home:login' %}">Log in</a></li>
              <li><a href="{% url 'home:signup' %}">Sign Up</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!-- Header Ends here -->

    {% block body %}

    {% endblock body %}

    <!-- Footer Starts Here -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="footer-item">
              <div class="footer-heading">
                <h2>About Us</h2>
              </div>
              <p>DC Space aim to facilitate your Property Portfolio Management & Investment. Get in touch to ask about your taylor made software.</p>
            </div>
          </div>
          
          <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="footer-item">
              <div class="footer-heading">
                <h2>Some Features</h2>
              </div>
              <ul class="footer-list">
                <li><a href="#">Accountancy</a></li>
                <li><a href="#">Communication</a></li>
                <li><a href="#">Marketing</a></li>
                <li><a href="#">Data Analisation</a></li>
                <li><a href="#">AI / Blockchain technologies</a></li>
              </ul>
            </div>
          </div>
          
          
          <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="footer-item">
              <div class="footer-heading">
                <h2>Navigation Links</h2>
              </div>
              <ul class="footer-list">
                <li><a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="{% url 'home:about' %}">About Us</a></li>
                <li><a href="{% url 'home:services' %}">Service</a></li>
                <li><a href="{% url 'home:contact' %}">Contact Us</a></li>
                <li><a href="{% url 'home:login' %}">Log-in</a></li>
              </ul>
            </div>
          </div>
          
          <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="footer-item">
              <div class="footer-heading">
                <h2>More Information</h2>
              </div>
              <ul class="footer-list">
                <li>Phone: <a href="#">+972-58-7898832</a></li>
                <li>Email: <a href="#">david.cusumano@hotmail.fr</a></li>
                <li>Support: <a href="#">support@DCSpace.com</a></li>
                <li>Website: <a href="#">www.DCSpace.com</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="sub-footer">
              <p>Copyright &copy; 2020 DC Space - Developed by David Cusumano</p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Footer Ends Here -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}" ></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>


    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>

src/project/home/templates/home/about.html
{% extends 'base.html'%}

    {% block body %}

    <!-- Page Content -->
    <!-- Heading Starts Here -->
    <div class="page-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>About Us</h1>
            <p><a href="index.html">Home</a> / <span>About Us</span></p>
          </div>
        </div>
      </div>
    </div>
    <!-- Heading Ends Here -->


    <!-- About Us Starts Here -->
    <div class="about-us">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="left-image">
              <img src="assets/images/our-team.jpg" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <div class="section-heading">
                <span>About Us</span>
                <h2>Background of our company</h2>
                <p>DC Space is the next ambitious prop-tech software that will enable you to grow your property portfolio. The company development started in Israel at Tel Aviv after a subsequent real estate market crash and the difficulty for individuals to keep up with their business goal, structure and organisation.</p>
              </div>
              <div id='tabs'>
                  <ul>
                    <li><a href='#tabs-1'>History</a></li>
                    <li><a href='#tabs-2'>Technology</a></li>
                    <li><a href='#tabs-3'>Partners</a></li>
                  </ul>
                  <section class='tabs-content'>
                    <article id='tabs-1'>
                      <p>From the office to the beach.
                      <br><br>Let's make things happen!</p>
                    </article>
                    <article id='tabs-2'>
                      <p>Automation robots, AI assistance, Blockchain transactions technologies, built-in CRM.
                      <br><br>The futur of Real Estate is happening now and thanks to the substential technological changes that happen this past 10years.</p>
                    </article>
                    <article id='tabs-3'>
                      <p>Developers Institute Israel, DC Lettings International, Space Finders London, MyAppartment.
                      <br><br>We are very grateful and thanksful to the above partners for believing in this project and allow us to make things happen.</p>
                    </article>
                  </section>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Us Ends Here -->

    <!-- Team Starts Here -->
    <div class="team-section">
      <div class="container">
        <div class="row">
          <div class="col-md-8 offset-md-2">
            <div class="section-heading">
              <span>Our Team</span>
              <h2>Meet the greatest people</h2>
              <p>See below our fast-growing and dynamic team.</p>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="team-item">
              <img src="assets/images/team-02.jpg" alt="">
              <div class="down-content">
                <h4>David Cusumano</h4>
                <span>Co-Founder</span>
              </div>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="team-item">
              <img src="assets/images/team-03.jpg" alt="">
              <div class="down-content">
                <h4>Avi Buchman</h4>
                <span>Head Project Manager</span>
              </div>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="team-item">
              <img src="assets/images/team-03.jpg" alt="">
              <div class="down-content">
                <h4>Adrien Mauriac</h4>
                <span>Co-Founder</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Team Ends Here -->

        <!-- Testimonials Starts Here -->
    <div class="testimonials-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <span>Testimonials</span>
              <h2>What they say about us</h2>
            </div>
          </div>
          <div class="col-md-10 offset-md-1">
            <div class="owl-testimonials owl-carousel">
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"At MyApartment Tel Aviv we have been working closely with the DC Space team to create our taylor made software to manage our fast growing portfolio! We cannot wait for this project to see the light."</p>
                <h4>William Smith</h4>
                <span>New Co-Founder</span>
              </div>
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"As a Senior Consultant Marketer, I can tell how communication and marketing has become more and more diverse because of multiple platform available. DC Space aim to centralise them all and it is going to save us valuable time."</p>
                <h4>Vinny Smart</h4>
                <span>Digital Marketer</span>
              </div>
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"Appart from the property industry, every industry has been digitalised in the past years. A big turn will happen soon in the real estate market and DC Space is trying to make it happen."</p>
                <h4>Trevor Liam</h4>
                <span>Technology Chef</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Testimonials Ends Here -->

{% endblock body %}

src/project/home/templates/home/contact.html
{% extends 'base.html'%}

    {% block body %}

    <!-- Page Content -->
    <!-- Heading Starts Here -->
    <div class="page-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>Contact Us</h1>
            <p><a href="index.html">Home</a> / <span>Contact Us</span></p>
          </div>
        </div>
      </div>
    </div>
    <!-- Heading Ends Here -->


    <!-- Contact Us Starts Here -->
    <div class="contact-us">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="contact-form">
              <form id="contact" action="" method="post">
                {% csrf_token %}
                <div class="row">
                  <div class="col-md-12 col-sm-12">
                    <fieldset>
                      <input name="name" type="text" id="name" placeholder="Your name" required="">
                    </fieldset>
                  </div>
                  <div class="col-md-12 col-sm-12">
                    <fieldset>
                      <input name="email" type="text" id="email" placeholder="Your email" required="">
                    </fieldset>
                  </div>
                  <div class="col-md-12 col-sm-12">
                    <fieldset>
                      <input name="subject" type="text" id="subject" placeholder="Subject">
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <textarea name="message" rows="6" id="message" placeholder="Your message" required=""></textarea>
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="main-button">Send Message</button>
                    </fieldset>
                  </div>
                </div>
              </form>
          </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <div class="section-heading">
                <span>Contact Us</span>
                <h2>Let's keep in touch</h2>
                <p>Quisque sagittis blandit sapien et elementum. Fusce pretium viverra consequat. Aliquam at feugiat mi. Pellentesque hendrerit, felis ac sodales commodo.</p>
              </div>
              <div class="row">
                <div class="col-md-6 col-sm-12">
                  <ul>
                    <li><i class="fa fa-phone"></i> 010-020-0560</li>
                    <li><i class="fa fa-support"></i> support@company.com</li>
                  </ul>
                </div>
                <div class="col-md-6 col-sm-12">
                  <ul>
                    <li><i class="fa fa-envelope"></i> contact@company.com</li>
                    <li><i class="fa fa-globe"></i> www.company.com</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Contact Us Ends Here -->


    <!-- Map Starts Here -->
    <div id="map">
    
<!-- How to change your own map point
	1. Go to Google Maps
	2. Click on your location point
	3. Click "Share" and choose "Embed map" tab
	4. Copy only URL and paste it within the src="" field below
-->

      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3381.160903577911!2d34.7722563!3d32.0648965!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151d4b86fecd5ddf%3A0x3f11d0c7b14bc712!2sDevelopers.Institute%20TLV%20(Developers%20Institute%20Coding%20Bootcamp%20%7C%206%20Campuses%2C%20No.%2031%20Ranked%20Worldwide%20%7C%20Learn%20to%20Code%20in%2012%20Weeks)!5e0!3m2!1sfr!2sil!4v1610019196472!5m2!1sfr!2sil" width="100%" height="520px" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <!-- Map Ends Here -->


    <!-- Testimonials Starts Here -->
    <div class="testimonials-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <span>Testimonials</span>
              <h2>What they say about us</h2>
            </div>
          </div>
          <div class="col-md-10 offset-md-1">
            <div class="owl-testimonials owl-carousel">
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"Ut elementum a elit sed tristique. Pellentesque sed semper erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean quam erat, rutrum ut malesuada."</p>
                <h4>William Smith</h4>
                <span>New Co-Founder</span>
              </div>
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"Quisque lacinia sed velit et maximus. Quisque dictum, lacus a malesuada finibus, arcu magna luctus risus, eu accumsan risus elit vitae lacus."</p>
                <h4>Vinny Smart</h4>
                <span>Digital Marketer</span>
              </div>
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"Vestibulum mauris ipsum, tempor tincidunt justo sit amet, bibendum tincidunt dui. Aenean molestie, odio quis viverra ultricies, leo tellus lacinia neque, sit amet maximus tortor nunc aliquet felis."</p>
                <h4>Trevor Liam</h4>
                <span>Technology Chef</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Testimonials Ends Here -->

    {% endblock body %}

src/project/home/templates/home/index.html
{% extends 'base.html'%}

    {% block body %}
    <!-- Page Content -->

    <!-- Banner Starts Here -->
    <div class="banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8 offset-md-2">
            <div class="header-text caption">
              <h2>Tired With Your Property Portfolio Organisation?</h2>
              <div id="search-section">
              	<form id="suggestion_form" name="gs" method="get" action="#">
                <div class="searchText">
                  <p style="color: white">DC Space is the right software for you. We aim to centralise and automatise all the aspects around your property portfolio management and investment.</p>
                </div>
                 </form>
               <div class="advSearch_chkbox">
               </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->


    <!-- Services Starts Here -->
    <div class="services-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <span>Hosting Services</span>
              <h2>Services we provide</h2>
              <p>DC Space is the new Prop-tech software game-changer for investors, property managers, agents and more. With us you will increase your efficiency in the same time as developing your Property Portfolio.</p>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="service-item">
              <i class="fa fa-database"></i>
              <h4>Centralise</h4>
              <p>Within one app we centralise all the aspects of your real estate portfolio. In fact, from finance to tenant communication, you will be able to get all your documents, finance statements, mortgage status, marketing templates and more... </p>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="service-item">
              <i class="fa fa-database"></i>
              <h4>Automate</h4>
              <p>We all know how communication and marketing can be quiet redundant tasks. This why with DC Space you will be able to generate email, messages and advertising templates in one place and all with AI assistance.</p>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="service-item">
              <i class="fa fa-database"></i>
              <h4>Analyse</h4>
              <p>In such a fast developing world, the data analization is what will allow you to get real time insights. This is the reasons why we decided to develop robots analysing and give you the best information to adjust and develop your investments strategy. </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Services Ends Here -->





    <!-- Features Starts Here -->
    <div class="features-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <span>Best Quality for you</span>
              <h2>Some of DC Space Features</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="feature-item">
              <div class="icon">
                <img src="assets/images/feature-01.png" alt="">
              </div>
              <h4>Cloud Storage</h4>
              <p>All your confidential documents, pictures, tenants contracts, invoices, statements and more in one place and highly secured.</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="feature-item">
              <div class="icon">
                <img src="assets/images/feature-01.png" alt="">
              </div>
              <h4>Easy Finance</h4>
              <p>With DC Space you don't need to be a accountant to take care of your own finance. Directly insert your finance data such as payments in interactive statements templates.</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="feature-item">
              <div class="icon">
                <img src="assets/images/feature-01.png" alt="">
              </div>
              <h4>AI Optimisation</h4>
              <p>An Ai friend will constantly analyse every aspects of you business in sending you notification, giving you insights and potential risks assessments.</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="feature-item">
              <div class="icon">
                <img src="assets/images/feature-01.png" alt="">
              </div>
              <h4>24/7 Assistance</h4>
              <p>Our team is available for you any time of the day and any day of the year by phone, mail or post. Encountering a particular difficulty? Get in touch with us, we will sort your issue within a record time.</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="feature-item">
              <div class="icon">
                <img src="assets/images/feature-01.png" alt="">
              </div>
              <h4>Blockchain Technology</h4>
              <p>The blockchain has secured what the financial system wouldn't have been able to. All your payments, contracts and information transmitted in a time record within a secure environment.</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="feature-item">
              <div class="icon">
                <img src="assets/images/feature-01.png" alt="">
              </div>
              <h4>Network Solutions</h4>
              <p>The digital era has never seen that much communication channel since our last global pandemic. Within the mobile app, tenants, agents, investors or anyone is welcome to take part in discussion places and network for the best. </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Features Ends Here -->

        <!-- Testimonials Starts Here -->
    <div class="testimonials-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <span>Testimonials</span>
              <h2>What they say about us</h2>
            </div>
          </div>
          <div class="col-md-10 offset-md-1">
            <div class="owl-testimonials owl-carousel">
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"At MyApartment Tel Aviv we have been working closely with the DC Space team to create our taylor made software to manage our fast growing portfolio! We cannot wait for this project to see the light."</p>
                <h4>William Smith</h4>
                <span>New Co-Founder</span>
              </div>
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"As a Senior Consultant Marketer, I can tell how communication and marketing has become more and more diverse because of multiple platform available. DC Space aim to centralise them all and it is going to save us valuable time."</p>
                <h4>Vinny Smart</h4>
                <span>Digital Marketer</span>
              </div>
              <div class="testimonial-item">
                <div class="icon">
                  <i class="fa fa-quote-right"></i>
                </div>
                <p>"Appart from the property industry, every industry has been digitalised in the past years. A big turn will happen soon in the real estate market and DC Space is trying to make it happen."</p>
                <h4>Trevor Liam</h4>
                <span>Technology Chef</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Testimonials Ends Here -->
    {% endblock body %}